# Generated by Django 2.1.5 on 2019-04-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='solicitud',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.Solicitudes'),
        ),
    ]
