# Generated by Django 2.1.5 on 2019-04-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20190409_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
