# Generated by Django 2.1.5 on 2019-04-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='solicitud',
        ),
    ]
