# Generated by Django 2.1.5 on 2019-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_remove_facturas_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='año',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='facturas',
            name='mes',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
