# Generated by Django 2.1.5 on 2019-04-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_auto_20190418_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='año',
            new_name='anio',
        ),
    ]
