# Generated by Django 2.1.5 on 2019-04-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_auto_20190418_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='anio',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='mes',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
