# Generated by Django 2.1.5 on 2019-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_auto_20190418_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
