# Generated by Django 2.1.5 on 2019-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_auto_20190425_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='folio',
            field=models.CharField(max_length=15),
        ),
    ]
