# Generated by Django 2.1.5 on 2019-04-25 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_auto_20190425_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanpages',
            name='zona',
        ),
    ]
