# Generated by Django 2.1.5 on 2019-04-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_remove_fanpages_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpages',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='solicitudes.Zonas'),
            preserve_default=False,
        ),
    ]
