# Generated by Django 2.1.5 on 2019-04-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_fanpages_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanpages',
            name='zona',
        ),
        migrations.AddField(
            model_name='fanpages',
            name='zonas',
            field=models.ManyToManyField(related_name='fan_zonas', to='solicitudes.Zonas'),
        ),
    ]
