# Generated by Django 2.1.5 on 2019-04-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_auto_20190426_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos',
            name='codename',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
    ]
